export const PLACE_QUERIES = [
  "551 Horai Kansai Airport",
  "AEON Bank Kansai Airport Terminal 1",
  "ASICS Factory Outlet Rinku",
  "ASICS Store Kyoto",
  "Aeon Mall Kyoto",
  "Brooklyn Roasting Company Rinku",
  "Ganko Sushi Kansai Airport",
  "Godiva Kansai Airport",
  "Grill Capital Touyoutei",
  "Higashi Honganji Temple",
  "Honke Owariya",
  "Hotel Vischio Kyoto by GRANVIA",
  "Inoda Coffee Kyoto",
  "Ippodo Tea Store Kyoto",
  "Izumo Kyoto Station",
  "JR Haruka Kansai Airport Station",
  "JR Haruka Kyoto Station",
  "JR Kyoto Isetan",
  "JR Ticket Office Kansai Airport Station",
  "Kamo River Kyoto",
  "Kansai International Airport",
  "Kansai International Airport Terminal 1",
  "Katsukura Kyoto Porta",
  "Kawaramachi Kyoto",
  "Kineya Mugimaru Kansai Airport",
  "Kinkaku-ji",
  "Komeraku Rinku",
  "Kura Sushi Rinku",
  "Kyogoku Kaneyo",
  "Kyoto Botanical Garden",
  "Kyoto Porta",
  "Kyoto Ramen Street",
  "Kyoto Station",
  "Kyoto Station Grand Stairway",
  "Kyoto Station Skyway",
  "Kyoto Tower",
  "Kyoto Tower Sando",
  "Kyoto Wakuden Isetan",
  "Lawson Kansai Airport Terminal 1",
  "Mametora Rinku Premium Outlets",
  "Marukyu Koyamaen Kyoto",
  "Moritaya JR Kyoto Isetan",
  "Nakamura Tokichi Kyoto Station",
  "Nana's Green Tea Kansai Airport",
  "Nakasu Kansai Airport",
  "Nakau Kyoto Station",
  "Nijo Castle",
  "Nishiki Market",
  "Omen Shijo",
  "Ootoya Kansai Airport",
  "Pontocho Alley",
  "Rinku Marble Beach",
  "Rinku Pleasure Town Seacle",
  "Rinku Premium Outlets",
  "Sanjusangendo",
  "Seven Bank Kansai Airport Terminal 1",
  "Shinkyogoku Shopping Street",
  "Sizuya Kyoto Station",
  "Smart Coffee Kyoto",
  "Starbucks Kansai Airport Terminal 1",
  "Teramachi Street Kyoto",
  "To-ji Temple",
  "Unagi Sora Kyoto",
  "Wako Kyoto Isetan",
  "Yakiniku Hiro Kyoto Station"
];
